version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  web:
    build: .
    command: rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

volumes:
  db_data:
